# Generated by Django 5.0 on 2023-12-19 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_number', models.CharField(max_length=8)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, help_text='Item price', max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, default=0, help_text='Item discount', max_digits=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('archived', models.BooleanField(default=False)),
            ],
        ),
    ]
